[package]
name = "riemann-rust-client"
version = "0.1.0"
authors = ["mcorbin <corbin.math@gmail.com>"]

[dependencies]
protobuf = "1.2.2"
clap = {version = "2.19", features =[ "yaml"]}
native-tls = "0.1"

[lib]
name = "rustmann"
path = "src/lib.rs"

[[bin]]
name = "rustmann"